services:
  frontend:
    build:
      context: ./../../fullstack-todo-list/Frontend
      dockerfile: dockerfile.frontend
    container_name: todo-frontend
    ports:
      - "9000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./../../fullstack-todo-list/Backend
      dockerfile: dockerfile.backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    # environment:
      

  
